### ISSUE TITLE
[Question] ub_resolve_async

### ISSUE THREAD

**Issue by alexzorin** [miekg/unbound#12]
Hi Miek,

Thanks for your DNS packages!

I just wanted to find out whether there were any technical reasons for why you chose not to implement the async functions from libunbound. Did you see any incompatibilities with the Go runtime?

I'm finding myself looking for a way to cancel unbound lookups (rather than ignoring them as `ResolveAsync` is currently implemented) and want to avoid repeating any work you might have already done.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/unbound] [Question] ub_resol..." ]
>Hi Miek,
>
>Thanks for your DNS packages!
>
>I just wanted to find out whether there were any technical reasons for why you chose not to implement the async functions from libunbound. Did you see any incompatibilities with the Go runtime?
>
>I'm finding myself looking for a way to cancel unbound lookups (rather than ignoring them as `ResolveAsync` is currently implemented) and want to avoid repeating any work you might have already done.

It's trivial to make the package concurrent (or 'async') by wrapping u.Resolve 
in a goroutine. So I don't see the benefit of exporting ResolveAsync?

**Comment by alexzorin** [comment]
The benefit in my case is to limit concurrent workload.

As I understand it, the workflow of using ub_resolve_async and ub_cancel allows queries that are still running to be cancelled.

In my project, I often see queries that run 5-10 minutes in duration due to Unbound's timeout behavior. If treat the query failed after e.g. 60s, I don't need unbound to continue working the query.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/unbound] [Question] ub_r..." ]
>The benefit in my case is to limit concurrent workload.
>
>As I understand it, the workflow of using ub_resolve_async and ub_cancel allows queries that are still running to be cancelled.
>
>In my project, I often see queries that run 5-10 minutes in duration due to 
>Unbound's timeout behavior.

that's a bit sad, I read the manpage just yet, but it doesn't mention any 
timeout settings in the context.

> If treat the query failed after e.g. 60s, I don't need unbound to continue working the query.

I like if there is olny one way of calling unbound from Go, so if Async is going 
to be the default, we need Resolve to use that as well and do the proper thing
with context.Context and a cancel function and all that.

**Comment by alexzorin** [comment]
I see, that's fair. I just wanted to know whether you'd avoided them for any other reason. Would be nice to see them in the project but I've got a plan to handle it another way for now. Thanks!

There's some more info on how Unbound handles timeouts on https://unbound.net/documentation/info_timeout.html
