### ISSUE TITLE
What's the license of this software?

### ISSUE THREAD

**Issue by oscarvalenzuelab** [miekg/unbound#14]
Hi!

I would love to use the wrapper for one of my projects, but I want to confirm what's the license for the project.

Unbound it's under BSD-3-Clause, should I consider the wrapper under the same license?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/unbound] What's the license ..." ]
>Hi!
>
>I would love to use the wrapper for one of my projects, but I want to confirm
>what's the license for the project.
>
>Unbound it's under BSD-3-Clause, should I consider the wrapper under the same
>license?

Hmm, good point. I'll add a license file, this would be the same as coredns, apache 2,
which I think is compatible with bsd-3 even.
