### ISSUE TITLE
memory leak (weird defer behaviour?)

### ISSUE THREAD

**Issue by tjeb** [miekg/unbound#8]
I noticed when resolving a lot of domains that memory consumption got rather large (coincidentally, around 5.6 million, but memory leaks also show at a mere 30000 calls to resolve).

I'm not sure why, but the defer C.ub_resolve_free(res) in https://github.com/miekg/unbound/blob/master/unbound.go#L209 does not seem to be working as intended; if I add a hard C.ub_resolve_free(res) before the final return statement the leak disappears (adding one at the error return does not have any effect; the defer does appear to work for that case).

valgrind output in the normal case, with 30000 queries (over 25 goroutines):

```
==4419== LEAK SUMMARY:
==4419==    definitely lost: 2,833,056 bytes in 29,511 blocks
==4419==    indirectly lost: 21,401,447 bytes in 141,458 blocks
==4419==      possibly lost: 50,590 bytes in 76 blocks
==4419==    still reachable: 476,493 bytes in 2,816 blocks
==4419==         suppressed: 0 bytes in 0 blocks
```

After adding C.ub_resolve_free(res) at line 277:

```
==4269== 
==4269== LEAK SUMMARY:
==4269==    definitely lost: 0 bytes in 0 blocks
==4269==    indirectly lost: 0 bytes in 0 blocks
==4269==      possibly lost: 8,928 bytes in 31 blocks
==4269==    still reachable: 16,466 bytes in 3 blocks
==4269==         suppressed: 0 bytes in 0 blocks
==4269== Rerun with --leak-check=full to see details of leaked memory
```

The leaks have a trace like:

```
==5581== 644,734 (45,600 direct, 599,134 indirect) bytes in 475 blocks are definitely lost in loss record 540 of 541
==5581==    at 0x4C2BBD5: calloc (vg_replace_malloc.c:711)
==5581==    by 0x4ED0FD8: context_new (context.c:144)
==5581==    by 0x4ED3E4B: ub_resolve (libunbound.c:668)
==5581==    by 0x60EB84: _cgo_d57b3cef5ebb_Cfunc_ub_resolve (unbound.go:421)
==5581==    by 0x45C4DF: runtime.asmcgocall (/usr/lib/go/src/runtime/asm_amd64.s:582)
==5581==    by 0x7: ???
==5581==    by 0xC8202CBA6F: ???
==5581==    by 0x4066F9: runtime.cgocall (/usr/lib/go/src/runtime/cgocall.go:110)
==5581==    by 0x4322BF: runtime.startTheWorldWithSema (/usr/lib/go/src/runtime/proc.go:983)
==5581==    by 0xC82001DFFF: ???
```

Not sure why this happens, my guess is either defer doesn't work as expected when used with C calls, or the main body messes with the pointer to the data in res calloced by libunbound... Adding the hard C.ub_resolve_free(res) appears to fix the issue but it does not seem very clean to me :)

**Comment by miekg** [comment]
Is that this? <https://github.com/golang/go/issues/15921>

killing the defer seems OK to me (with a comment, maybe with Go 1.8 we can reintroduce it)
